apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-secret
spec:
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: wordpress-secret
  data:
    - secretKey: password
      remoteRef:
        key: wordpress-db-secret
        property: password